// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbSIOvH2TXwq_yj1n5yul3tdXnKdbDGvw',
    appId: '1:354014270351:android:109a2610be85fbf972b1fa',
    messagingSenderId: '354014270351',
    projectId: 'crudfirebase-5faa0',
    storageBucket: 'crudfirebase-5faa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtf6FjKPaoNY2q3OS6JnRzNetetpuJrY',
    appId: '1:354014270351:ios:e853c8a1be9ff86372b1fa',
    messagingSenderId: '354014270351',
    projectId: 'crudfirebase-5faa0',
    storageBucket: 'crudfirebase-5faa0.appspot.com',
    iosClientId: '354014270351-7slmiejb4svqco1bj5fgmgin55kfidce.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDeHYLRgznMWG4FkUxfU7K_U6gYDsbHU',
    appId: '1:354014270351:web:21c9023cd0a3e1a572b1fa',
    messagingSenderId: '354014270351',
    projectId: 'crudfirebase-5faa0',
    authDomain: 'crudfirebase-5faa0.firebaseapp.com',
    storageBucket: 'crudfirebase-5faa0.appspot.com',
    measurementId: 'G-ZQLPBQR7S5',
  );

}